#!/bin/bash
#
# ==================================================
cd
cat > /etc/apt/sources.list <<-END
deb http://kartolo.sby.datautama.net.id/debian/ bullseye main contrib non-free
deb http://kartolo.sby.datautama.net.id/debian/ bullseye-updates main contrib non-free
deb http://kartolo.sby.datautama.net.id/debian-security/ bullseye/updates main contrib non-free

END

apt update
apt list --upgradeable
apt upgrade
